version: "3.9"
services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DB_SOURCE=postgresql://postgres:admin@postgres:5434/user?sslmode=disabled

  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=user